services:
  - type: web
    name: poxel-io
    runtime: node
    plan: free
    rootDir: myarc2.0/poxel-io
    buildCommand: npm install
    startCommand: npm start
    healthCheckPath: /health
